# Generated by Django 3.1.5 on 2021-02-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=150)),
                ('first_option', models.CharField(max_length=70)),
                ('second_option', models.CharField(max_length=70)),
                ('third_option', models.CharField(max_length=70)),
                ('fourth_option', models.CharField(max_length=70)),
                ('correct_answer', models.IntegerField(default=0)),
            ],
        ),
    ]
